dev:
  doctrine:
    param:
      classname:  DebugPDO

test:
  doctrine:
    param:
      classname:  DebugPDO

all:
  doctrine:
    class:        sfDoctrineDatabase
    param:
      classname:  DoctrinePDO
      dsn:        mysql:dbname=hin;host=localhost
      username:   sf
      password:   sfiii
      encoding:   utf8
      persistent: true
      pooling:    true
