<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseHM extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('h_m');
        $this->hasColumn('hin_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('model_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Hin', array(
             'local' => 'hin_id',
             'foreign' => 'id'));

        $this->hasOne('Model', array(
             'local' => 'model_id',
             'foreign' => 'id'));
    }
}