<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseModel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('model');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('Hin as Hins', array(
             'refClass' => 'HM',
             'local' => 'model_id',
             'foreign' => 'hin_id'));

        $this->hasMany('HM as HMs', array(
             'local' => 'id',
             'foreign' => 'model_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}