<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HinTable extends Doctrine_Table
{
	public static function getAll()
	{
		$a = Doctrine_Query::create()
		->from('Hin j');
		
		return $a;
	}
	public static function getPager()
	{
		$a = Doctrine_Query::create()
		->from('Hin j');
		$count = count($a) / 30;
		$count = floor($count) + 1;
		$range = range(1 , $count);
		return $range;
	}
	public static function moveLast()
	{
		$a = Doctrine_Query::create()
		->from('Hin j');
		$count = count($a) / 30;
		$count = floor($count) + 1;
		
		return $count;
	}
	public static function idPage($id)
	{
		if($id%30 == 0){
			$page = $id / 30;
		}
		else{
			$page = floor($id / 30);
			$page = $page + 1;
		}
		return $page;
	}
	public static function getCount()
	{
		$a = Doctrine_Query::create()
		->from('Hin j');
		
		$count = count($a);
		return $count;
	}

}