<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModelTable extends Doctrine_Table
{
	public static function getName()
	{
		$a = Doctrine_Query::create()
		->from('Model m')->orderBy('m.name')->execute();
		foreach($a as $a){
			$model[$a['id']] = $a['name'];
		}
		return $model;
	}
	
	public static function getId()
	{
		$a = Doctrine_Query::create()
		->from('Model m')->orderBy('m.name')->execute();
		foreach($a as $a){
			$model[$a['id']] = $a['id'];
		}
		return $model;
	}

}